[package]
name = "clockAnalog"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.43"
iced = { version = "0.14", features = ["canvas", "tokio"] }
tokio = { version = "1", features = ["time"] }
